=== readywer/DIZ4VX_XMLGyak/DIZ4VX_1004/DIZ4VX_ertodtd.dtd
<!ELEMENT DIZ4VX_modell (A+,  B+ , C+,  AB*)>

<!ELEMENT A (b+, c)>
<!ATTLIST A a ID #REQUIRED>
<!ELEMENT b (#PCDATA | x | y)*>
<!ELEMENT x (#PCDATA)>
<!ELEMENT y (#PCDATA)>
<!ELEMENT c (#PCDATA | d | e)*>
<!ELEMENT d (#PCDATA)>
<!ELEMENT e (#PCDATA)>

<!ELEMENT B (b)>
<!ATTLIST B 
        a ID #REQUIRED
        c IDREF #REQUIRED>

<!ELEMENT C (b)>
<!ATTLIST C a ID #REQUIRED>

<!ELEMENT AB (c)>
<!ATTLIST AB 
        aref IDREF #REQUIRED
        bref IDREF #REQUIRED>

=== readywer/DIZ4VX_XMLGyak/DIZ4VX_1004/DIZ4VX_dtdtoxml.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE DIZ4VX_modell SYSTEM "DIZ4VX_ertodtd.dtd">
<DIZ4VX_modell>
    <A a="a1">
        <b>
            <x></x>
            <y></y>
        </b>
        <b>
            <x></x>
            <y></y>
        </b>
        <c>
            <d></d>
            <e></e>
        </c>
    </A>
    <B a="b1" c="c1">
        <b>
            <x></x>
            <y></y>
        </b>
    </B>
    <C a="c1">
        <b></b>
    </C>
    <AB aref="a1" bref="b1">
        <c></c>
    </AB>
</DIZ4VX_modell>
