=== readywer/DIZ4VX_XMLGyak/DIZ4VX_1004/DIZ4VX_kurzusfelvetel.dtd
<!ELEMENT kurzusfelvetel (kurzus*, idopont+, (oktato|oraado)?, jovahagyas)>
<!ELEMENT kurzus (kurzuskod, kurzusnev)>
    <!ELEMENT kurzuskod (#PCDATA)>
    <!ELEMENT kurzusnev (#PCDATA)>
<!ELEMENT idopont (nap, ora)>
    <!ELEMENT nap (#PCDATA)>
    <!ELEMENT ora (#PCDATA)>
<!ELEMENT oktato (#PCDATA)>
<!ELEMENT oraado (#PCDATA)>
<!ELEMENT jovahagyas (#PCDATA)>
<!ATTLIST jovahagyas alapertelmezett (igen|nem) "nem">

=== readywer/DIZ4VX_XMLGyak/DIZ4VX_1004/DIZ4VX_kurzusfelvetel.xml
<?xml version="1.0"?>
<!DOCTYPE kurzusfelvetel SYSTEM "DIZ4VX_kurzusfelvetel.dtd">
<kurzusfelvetel>
    <kurzus>
        <kurzuskod>K123</kurzuskod>
        <kurzusnev>Matematika I.</kurzusnev>
    </kurzus>
    <kurzus>
        <kurzuskod>K456</kurzuskod>
        <kurzusnev>Fizika II.</kurzusnev>
    </kurzus>
    <idopont>
        <nap>Hétfő</nap>
        <ora>10:00</ora>
    </idopont>
    <idopont>
        <nap>Szerda</nap>
        <ora>14:30</ora>
    </idopont>
    <oktato>Dr. Kovács Péter</oktato>
    <jovahagyas>igen</jovahagyas>
</kurzusfelvetel>
