=== readywer/DIZ4VX_XMLGyak/DIZ4VX_1018/XMLSchema_DIZ4VX.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="név" type="xs:string" />
    <xs:element name="helyszín" type="xs:string" />
    <xs:element name="év" type="xs:gYear" />
    <xs:element name="adószám" type="adószámTípus" />
    <xs:element name="alapítás" type="xs:gYear" />
    <xs:element name="bevétel" type="xs:integer" />
    <xs:element name="ország" type="xs:string" />
    <xs:element name="díj" type="xs:int" />
    <xs:element name="ital" type="xs:string" />
    <xs:element name="cég" type="xs:string" />
    <xs:element name="műszak" type="xs:string" />
    <xs:element name="fizetés" type="xs:int" />
    <xs:element name="diákigazolvány" type="diákigazolványTípus" />
    <xs:element name="nyelv" type="xs:string" />
    <xs:element name="szint" type="nyelvSzintTipus" />
    <xs:element name="kérdező" type="xs:string" />

    <xs:simpleType name="nyelvSzintTipus">
        <xs:restriction base="xs:string">
            <xs:enumeration value="A1" />
            <xs:enumeration value="A2" />
            <xs:enumeration value="B1" />
            <xs:enumeration value="B2" />
            <xs:enumeration value="C1" />
            <xs:enumeration value="C2" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="adószámTípus">
        <xs:restriction base="xs:string">
            <xs:pattern value="(\d{8})-(\d)-(\d{2})" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="diákigazolványTípus">
        <xs:restriction base="xs:string">
            <xs:length value="11" />
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="fesztiválTípus">
        <xs:sequence>
            <xs:element ref="név" />
            <xs:element ref="helyszín" />
            <xs:element ref="év" />
        </xs:sequence>
        <xs:attribute name="Fesz_ID" type="xs:integer" use="required" />
    </xs:complexType>
    <xs:complexType name="tulajdonosTípus">
        <xs:sequence>
            <xs:element ref="név" />
            <xs:element ref="adószám" />
            <xs:element ref="alapítás" />
            <xs:element ref="bevétel" />
        </xs:sequence>
        <xs:attribute name="T_ID" type="xs:integer" use="required" />
        <xs:attribute name="Fesztivál" type="xs:integer" use="required" />
    </xs:complexType>
    <xs:complexType name="fellépőTípus">
        <xs:sequence>
            <xs:element ref="név" />
            <xs:element ref="ország" />
            <xs:element ref="díj" />
        </xs:sequence>
        <xs:attribute name="Fel_ID" type="xs:integer" use="required" />
        <xs:attribute name="Fesztivál" type="xs:integer" use="required" />
    </xs:complexType>
    <xs:complexType name="bárTípus">
        <xs:sequence>
            <xs:element ref="név" />
            <xs:element ref="ital" minOccurs="1" maxOccurs="unbounded" />
            <xs:element ref="cég" />
        </xs:sequence>
        <xs:attribute name="B_ID" type="xs:integer" use="required" />
        <xs:attribute name="Fesztivál" type="xs:integer" use="required" />
    </xs:complexType>
    <xs:complexType name="alkalmazottTípus">
        <xs:sequence>
            <xs:element ref="név" />
            <xs:element ref="műszak" minOccurs="1" maxOccurs="3" />
            <xs:element ref="fizetés" />
        </xs:sequence>
        <xs:attribute name="A_ID" type="xs:integer" use="required" />
        <xs:attribute name="Munkahely" type="xs:integer" use="required" />
    </xs:complexType>
    <xs:complexType name="résztvevőTípus">
        <xs:sequence>
            <xs:element ref="név" />
            <xs:element ref="diákigazolvány" minOccurs="0" maxOccurs="1"/>
            <xs:element name="lakcím">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="település" type="xs:string" />
                        <xs:element name="utca" type="xs:string" />
                        <xs:element name="házszám" type="xs:integer" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="R_ID" type="xs:integer" use="required" />
        <xs:attribute name="Fesztivál" type="xs:integer" use="required" />
    </xs:complexType>
    <xs:complexType name="nyelvtudásTípus">
        <xs:sequence>
            <xs:element ref="nyelv" />
            <xs:element ref="szint" />
        </xs:sequence>
        <xs:attribute name="Ny_ID" type="xs:integer" use="required" />
    </xs:complexType>
    <xs:complexType name="közvéleményTípus">
        <xs:sequence>
            <xs:element ref="kérdező"/>
        </xs:sequence>
        <xs:attribute name="K_ID" type="xs:integer" use="required" />
        <xs:attribute name="megkérdezett" type="xs:integer" use="required" />
        <xs:attribute name="nyelvtudás" type="xs:integer" use="required" />
    </xs:complexType>

    <xs:element name="Fesztivál_DIZ4VX">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="fesztivál" type="fesztiválTípus" minOccurs="0" maxOccurs="2"/>
                <xs:element name="tulajdonos" type="tulajdonosTípus" minOccurs="0" maxOccurs="2"/>
                <xs:element name="fellépő" type="fellépőTípus" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="bár" type="bárTípus" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="alkalmazott" type="alkalmazottTípus" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="résztvevő" type="résztvevőTípus" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="nyelvtudás" type="nyelvtudásTípus" minOccurs="0" maxOccurs="10"/>
                <xs:element name="közvélemény" type="közvéleményTípus" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
        

        <xs:key name="fesztivál_kulcs">
            <xs:selector xpath="Fesztivál"/>
            <xs:field xpath="@Fel_ID"/>
        </xs:key>
        <xs:key name="tulajdonos_kulcs">
            <xs:selector xpath="tulajdonos"/>
            <xs:field xpath="@T_ID"/>
        </xs:key>
        <xs:key name="fellépő_kulcs">
            <xs:selector xpath="fellépő"/>
            <xs:field xpath="@Fel_ID"/>
        </xs:key>
        <xs:key name="bár_kulcs">
            <xs:selector xpath="bár"/>
            <xs:field xpath="@B_ID"/>
        </xs:key>
        <xs:key name="alkalmazott_kulcs">
            <xs:selector xpath="alkalmazott"/>
            <xs:field xpath="@A_ID"/>
        </xs:key>
        <xs:key name="résztvevő_kulcs">
            <xs:selector xpath="résztvevő"/>
            <xs:field xpath="@R_ID"/>
        </xs:key>
        <xs:key name="nyelvtudás_kulcs">
            <xs:selector xpath="nyelvtudás"/>
            <xs:field xpath="@Ny_ID"/>
        </xs:key>
        <xs:key name="közvélemény_kulcs">
            <xs:selector xpath="közvélemény"/>
            <xs:field xpath="@K_ID"/>
        </xs:key>

        <xs:keyref name="fesztivál_tulaj_kulcs" refer="fesztivál_kulcs">
            <xs:selector xpath="tulajdonos"/>
            <xs:field xpath="@fesztivál"/>
        </xs:keyref>
        <xs:keyref name="fesztivál_bár_kulcs" refer="fesztivál_kulcs">
            <xs:selector xpath="bár"/>
            <xs:field xpath="@fesztivál"/>
        </xs:keyref>
        <xs:keyref name="fesztivál_résztvevő_kulcs" refer="fesztivál_kulcs">
            <xs:selector xpath="résztvevő"/>
            <xs:field xpath="@fesztivál"/>
        </xs:keyref>
        <xs:keyref name="fesztivál_fellépő_kulcs" refer="fesztivál_kulcs">
            <xs:selector xpath="fellépő"/>
            <xs:field xpath="@fesztivál"/>
        </xs:keyref>
        <xs:keyref name="bár_alkalmazott_kulcs" refer="bár_kulcs">
            <xs:selector xpath="alkalmazott"/>
            <xs:field xpath="@munkahely"/>
        </xs:keyref>
        <xs:keyref name="nyelvtudás_közvélemény_kulcs" refer="nyelvtudás_kulcs">
            <xs:selector xpath="közvélemény"/>
            <xs:field xpath="@nyelvtudás"/>
        </xs:keyref>
        <xs:keyref name="résztvevő_közvélemény_kulcs" refer="résztvevő_kulcs">
            <xs:selector xpath="közvélemény"/>
            <xs:field xpath="@megkérdezett"/>
        </xs:keyref>

        <xs:unique name="fesztivál_tulaj_egyegy">
            <xs:selector xpath="tulajdonos"/>
            <xs:field xpath="@fesztivál"/>
        </xs:unique>

    </xs:element>
</xs:schema>

=== readywer/DIZ4VX_XMLGyak/DIZ4VX_1018/XML_DIZ4VX.xml
<?xml version="1.0" encoding="UTF-8"?>

<Fesztivál_DIZ4VX xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="XMLSchema_DIZ4VX.xsd">
    <fesztivál feszkód="1">
        <név>Strand Fesztivál</név>
        <helyszín>Zamádi</helyszín>
        <év>2023</év>
    </fesztivál>
    <fesztivál feszkód="2">
        <név>Kocsonyafesztivál</név>
        <helyszín>Miskolc</helyszín>
        <év>2023</év>
    </fesztivál>

    <tulajdonos tkód="11" fesztivál="1">
        <név>Sziget Kulturális Menedzser Iroda Zártkörűen Működő Részvénytársaság</név>
        <adószám>12345678-8-69</adószám>
        <alapítás>2000</alapítás>
        <bevétel>46868000</bevétel>
    </tulajdonos>
    <tulajdonos tkód="12" fesztivál="2">
        <név>Miskolc Város Önkormányzata</név>
        <adószám>112345678-5-55</adószám>
        <alapítás>1990</alapítás>
        <bevétel>97476127</bevétel>
    </tulajdonos>

    <fellépő felkód="21" fesztivál="1">
        <név>Ákos</név>
        <ország>Magyarország</ország>
        <díj>500000</díj>
    </fellépő>
    <fellépő felkód="22" fesztivál="2">
        <név>Tiesto</név>
        <ország>Hollandia</ország>
        <díj>800000</díj>
    </fellépő>

    <bár bkód="31" fesztivál="1">
        <név>Fit-Nes</név>
        <ital>vadász</ital>
        <ital>pálinka</ital>
        <ital>bor</ital>
        <ital>rum</ital>
        <cég>Vicc kft.</cég>
    </bár>
    <bár bkód="32" fesztivál="2">
        <név>Korozó</név>
        <ital>sör</ital>
        <ital>bor</ital>
        <ital>házmester</ital>
        <ital>pálinka</ital>
        <cég>Korozó kft.</cég>
    </bár>

    <alkalmazott akód="41" munkahely="31">
        <név>Farkas Cintia</név>
        <muszak>8-20</muszak>
        <fizetés>200000</fizetés>
    </alkalmazott>
    <alkalmazott akód="42" munkahely="32">
        <név>Bukta Laura</név>
        <muszak>20-4</muszak>
        <muszak>8-12</muszak>
        <fizetés>300000</fizetés>
    </alkalmazott>

    <résztvevő rkód="51" fesztivál="1">
        <név>Badány gábor</név>
        <diákigazolvány>123456789</diákigazolvány>
        <lakcím>
            <település>Miskolc</település>
            <utca>Alma</utca>
            <házszám>10</házszám>
        </lakcím>
    </résztvevő>
    <résztvevő rkód="52" fesztivál="2">
        <név>Farkas Balázs</név>
        <lakcím>
            <település>Budapest</település>
            <utca>Köd</utca>
            <házszám>1</házszám>
        </lakcím>
    </résztvevő>

    <nyelvtudás nykód="61">
        <nyelv>angol</nyelv>
        <szint>B2</szint>
    </nyelvtudás>
    <nyelvtudás nykód="62">
        <nyelv>német</nyelv>
        <szint>B2</szint>
    </nyelvtudás>

    <közvélemény kkód="71" megkérdezett="51" nyelvtudás="61">
        <kérdező>Forgács Beatrix</kérdező>
    </közvélemény>
    <közvélemény kkód="72" megkérdezett="52" nyelvtudás="62">
        <kérdező>Forgács Beatrix</kérdező>
    </közvélemény>
</Fesztivál_DIZ4VX>
